parameters:
#    wilson_hello.example.class: Wilson\HelloBundle\Example

services:
#    wilson_hello.example:
#        class: %wilson_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
